### ISSUE TITLE
Add meta support

### ISSUE THREAD

**Issue by tmcw** [documentationjs/documentation-theme-default#8]
- [x] `@version` http://usejsdoc.org/tags-version.html
- [x] `@since` http://usejsdoc.org/tags-since.html
- [x] `@author` http://usejsdoc.org/tags-author.html
- [x] `@copyright` http://usejsdoc.org/tags-copyright.html
- [x] `@license` http://usejsdoc.org/tags-license.html

I just added these to core, we should add them here too. Refs https://github.com/documentationjs/documentation/issues/9
